import java.util.LinkedList;
import java.util.List;
import java.util.Scanner;

import exceptions.ScriptException;
import script.Parser;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        List<Player> players = new LinkedList<>();
        Parser parser = new Parser();

        parser.registerComand("add_p", (a)->{
            int x = Integer.parseInt(a.get("x"));
            int y = Integer.parseInt(a.get("y"));
            String name = a.get("name");
            players.add(new Player(x, y, name));
        });
        parser.execute("$X 4");
        parser.execute("add_p x 0, y $X, name ABOBUS");
        

        Scanner sc = new Scanner(System.in);
        while(sc.hasNextLine()){
            try{
                parser.executeLine(sc.nextLine());
            } catch (ScriptException e){
                System.out.println(e.getMessage());
            }
        }
        for(Player p : players){
            System.out.println(p);
        }
    }
}
